### ISSUE TITLE
[4.2] Public Link for directory is broken if "enable search in minisite is turned on"

### ISSUE THREAD

**Issue by Fred-Hau** [pydio/cells#487] opened 2023-05-23 11:05 UTC
**📝 Describe the bug**

Since the 4.2 update, there is no longer the possibility of publicly sharing a directory or a cell.
I can publicly share a file but not the directory containing the public files.
A blank page is displayed and I have no error in the log

**⚙️ How-to Reproduce**

1 -Go on directory Share, active public shared.
2- Copy the link
3- Paste on private navigate

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version 4.2.1
 - OS/Arch:       linux/amd64 Debian 11
  Go version:    go1.19.9

Client used for testing: 
 - Browser Firefox safari, Edge
 
 
Additional context:
 - Datasource type : Flat/ Local storage

**Comment by cdujeu** [comment] 2023-05-23 11:08
Argh - seems like your the second person seeing this issue. Not good.. 
I guess you see errors if you load the link with your browser "Developer Console" (generally F12) opened?

**Comment by Fred-Hau** [comment] 2023-05-23 11:22
Hello,
Yes I got this error :
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
and many llines of error like this : 
https://X.X.X.X/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=22d853db4064a4fa9838f0a350472941:2
Do you need other informations ?

**Comment by cdujeu** [comment] 2023-05-23 12:06
can you send all the details of the "share link" dialog : label, password protected or not, link layout, was it created before or after upgrade to 4.2, etc... 
Does your instance have specific settings (like custom user-defined metadata, etc..) ? 
Just can't reproduce it on many different instances as of now, but probably missing something...

**Comment by Fred-Hau** [comment] 2023-05-23 12:56
label : intranet (I try with the default label)
No password protected
Link layout ??
It was created before and I try with a new creation after update.
No specific setting, all by default.
Merci

**Comment by cdujeu** [comment] 2023-05-23 13:05
Would you mind creating a temp user for me on your instance so that I try creating a link by myself? you can DM me with my first name (at) the domain name ;-)

**Comment by cdujeu** [comment] 2023-06-20 15:25
was fixed in 4.2.2

**Closed by cdujeu** 2023-06-20 15:25 UTC
Labels: bug
