### ISSUE TITLE
pydio.grpc.mailer default from setting has no effect

### ISSUE THREAD

**Issue by FraEgg** [pydio/cells#304] opened 2021-03-04 17:32 UTC
When a userprofile has a e-mailaddress "Allways send from the DEFAULT From Address/Name" settings in the config has no effect. Every mail send with the userprofile e-mail address.

Pydio Cells 2.2.2

Cu

**Comment by fajo-de** [comment] 2021-03-04 18:34
Some futher diagnostics show that for notifications the setting is honoured - invitations and test messages however always use the users mail address now (worked as designed up to 2.1.6)

**Comment by cdujeu** [comment] 2021-03-08 14:41
Hi, 
I cannot reproduce this - do you correctly wait for mailer service to restart after changing configurations? 
Could you otherwise provide a full scenario to reproduce the issue? 
Thx

**Comment by cdujeu** [comment] 2021-03-08 14:57
[edit] it seems that the From **email** is correct but no the From **Name**, can you confirm that?

**Comment by fajo-de** [comment] 2021-03-08 16:57
Hi Charles,

according to my gateway logs the envelope too contains the wrong email address (along with the From: header). This only happens when sending a test messages (mailer settings page in the console) and when sending an invitation for a share/cell. Notifications on watches use the right sender addresses.

The setting used is "Always send from the Default FROM address/name". This should cause the configured default address/name to be used when sending any kind of emails. This wored in 2.1 (2.1.6 is my latest) but fails in 2.2.2.

I have not yet found where this could go wrong, but am still searching the code (too busy currently to speed this up).

**Comment by cdujeu** [comment] 2021-03-10 17:05
Should now be fixed in 2.2.3

**Closed by cdujeu** 2021-03-10 17:05 UTC
